export const CATEGORIES = [
    { name: "Food", icon: "🍔", color: "#FFD700" },
    { name: "Bills/Utilities", icon: "💡", color: "#FFA07A" },
    { name: "Family", icon: "👨‍👩‍👧‍👦", color: "#90EE90" },
    { name: "Healthcare", icon: "🏥", color: "#FF7F7F" },
    { name: "Fuel", icon: "⛽", color: "#FF8C00" },
    { name: "Phone/Internet", icon: "📱", color: "#87CEEB" },
    { name: "Education", icon: "📚", color: "#9370DB" },
    { name: "Entertainment", icon: "🎬", color: "#E6E6FA" },
    { name: "Shopping", icon: "🛍️", color: "#FF69B4" },
    { name: "Travel", icon: "✈️", color: "#00CED1" },
    { name: "Socializing", icon: "🍻", color: "#CD853F" },
    { name: "Withdrawal", icon: "🏧", color: "#D3D3D3" },
    { name: "Transfer", icon: "💸", color: "#32CD32" },
    { name: "Transportation", icon: "🚗", color: "#FFA500" },
    { name: "Housing", icon: "🏠", color: "#ADD8E6" },
    { name: "Miscellaneous", icon: "📦", color: "#808080" },
];